export type {
	McpCatalogCapability,
	McpCatalogSection,
	McpCatalogSnapshot,
	McpCatalogStatus,
} from "./client/catalog.ts";
export {
	MCP_HTTP_RECONNECTION_DEFAULTS,
	McpClientSession,
	McpConnectionDefinition,
	createOfficialClient,
	defineConnection,
	httpConnection,
	inProcessConnection,
	normalizeRoots,
	sseConnection,
} from "./client/connection.ts";
export type {
	McpAutoRefreshOptions,
	McpCapabilityExtensions,
	McpClientAdvertise,
	McpKeepaliveOptions,
	McpReconnectBackoffOptions,
	McpReconnectOptions,
	McpResolvedAutoRefreshOptions,
	McpResolvedKeepaliveOptions,
	McpResolvedReconnectOptions,
	McpClientNotificationHandlers,
	McpClientNotificationMethod,
	McpClientRequestHandlers,
	McpClientRequestMethod,
	McpConnectionDefinitionOptions,
	McpHttpAuth,
	McpHttpConnectionOptions,
	McpHttpResumeOptions,
	McpInProcessConnectionOptions,
	McpInProcessServer,
	McpOfficialClientOverrides,
	McpRequestDefaults,
	McpResolvedResumedSession,
	McpResumedSession,
	McpRootsSource,
	McpSseConnectionOptions,
	McpTransportFactory,
	McpTransportKind,
} from "./client/connection.ts";
export {
	InMemoryKeyValueStore,
	McpOAuthClientProvider,
	identityFromClaims,
	normalizeScope,
	oauthTokensExpireWithin,
} from "./client/oauth.ts";
export type {
	McpCallbackStateVerifier,
	McpKeyValueStore,
	McpOAuthClientProviderOptions,
	McpOAuthCredentialStatus,
	McpOAuthRefreshOptions,
	McpStoredOAuthTokens,
} from "./client/oauth.ts";
export {
	MCP_CLIENT_CREDENTIALS_EXTENSION,
	MCP_DEFAULT_IDP_SCOPE,
	MCP_ENTERPRISE_MANAGED_AUTH_EXTENSION,
	MCP_ID_JAG_GRANT_PROFILE,
	MCP_PRIVATE_KEY_JWT_ALGORITHMS,
	assertCallbackSucceeded,
	authorizeEnterpriseIdp,
	authorizeOAuth,
	clientCredentialsAuth,
	enterpriseManagedAuth,
	explainOAuthError,
	oauthGrantOf,
	oauthServerUrl,
	pinnedDiscoveryState,
	refreshIdpTokens,
	serverAcceptsIdJag,
	validateOAuthCredentials,
} from "./client/oauth-flows.ts";
export type {
	McpAuthorizeOAuthOptions,
	McpAuthorizeOAuthResult,
	McpClientCredentialsOptions,
	McpEnterpriseManagedAuthOptions,
	McpIdpAuthorizationOptions,
	McpIdpAuthorizationResult,
	McpIdpTokens,
	McpOAuthFailure,
	McpOAuthFailureKind,
	McpOAuthGrant,
	McpRefreshIdpTokensOptions,
	McpValidateCredentialsOptions,
	McpValidatedCredentials,
} from "./client/oauth-flows.ts";
export { KeyringKeyValueStore } from "./client/keyring.ts";
export type { McpKeyringEntry, McpKeyringStoreOptions } from "./client/keyring.ts";
export { decodeJwtClaims, jwtExpiresAt } from "./client/jwt.ts";
export type { McpJwtClaims } from "./client/jwt.ts";
export {
	MCP_TASK_TERMINAL_STATUSES,
	McpTaskClient,
	McpTaskFailedError,
	assertTasksAvailable,
	supportsToolTasks,
} from "./client/tasks.ts";
export type {
	McpCreateToolTaskOptions,
	McpTaskPollOptions,
	McpTaskRequester,
	McpTaskUpdate,
} from "./client/tasks.ts";
export {
	MCP_SKILLS_EXTENSION_KEY,
	MCP_SKILLS_INDEX_URI,
	discoverSkills,
	parseSkillsIndex,
	resolveSkillUri,
	skillTextContent,
	skillsFromResources,
} from "./client/skills.ts";
export type { McpSkill, McpSkillReader, McpSkillType } from "./client/skills.ts";
export { decodeResourceContent } from "./client/resources.ts";
export type { McpDecodeResourceOptions, McpDecodedResourceContent } from "./client/resources.ts";
export { checkPromptContract, checkToolContract } from "./client/contract.ts";
export type {
	McpContractMode,
	McpContractResult,
	McpExpectedPrompt,
	McpExpectedTool,
	McpPromptContractOptions,
	McpSchemaShape,
	McpToolContractOptions,
} from "./client/contract.ts";
export {
	MCP_LEGACY_PROTOCOL_VERSIONS,
	MCP_MODERN_PROTOCOL_VERSION,
	MCP_SUPPORTED_PROTOCOL_VERSIONS,
	isModernProtocolVersion,
	resolveProtocolPin,
} from "./internal/protocol.ts";
export type { McpProtocolEra, McpProtocolPin } from "./internal/protocol.ts";
export {
	McpConnectionManager,
	McpPromptContractError,
	McpToolCallError,
	McpToolContractError,
	describeError,
	parseToolResult,
	resumedSessionFrom,
	throwIfToolError,
} from "./client/manager.ts";
export type {
	McpCallToolOptions,
	McpCallToolParsedOptions,
	McpConnectAllOptions,
	McpConnectionEvent,
	McpConnectionEventType,
	McpConnectionListener,
	McpConnectionManagerOptions,
	McpConnectionManagerSnapshot,
	McpConnectionMode,
	McpConnectionOperationControl,
	McpConnectionPhase,
	McpConnectionSnapshot,
	McpContractOptions,
	McpErrorDetail,
	McpGetPromptOptions,
	McpKeepaliveSnapshot,
	McpMetaOptions,
	McpMrtrForwardOptions,
	McpParsedToolResult,
	McpPingResult,
	McpPromptContractOption,
	McpReadOptions,
	McpRequestOptionsWithMeta,
	McpToolContractOption,
	McpWatchSnapshot,
} from "./client/manager.ts";

// Curated official SDK v2 client surface so driving a kmcp connection needs no second import.
// Names the server entry already re-exports (errors shared through the core package, result and
// content types) are deliberately absent here: the package root star-exports both entries.
export {
	AuthorizationServerMismatchError,
	Client,
	ClientCredentialsProvider,
	CrossAppAccessProvider,
	InMemoryResponseCacheStore,
	InMemoryTransport,
	InsecureTokenEndpointError,
	InsufficientScopeError,
	IssuerMismatchError,
	OAuthClientFlowError,
	OAuthError,
	OAuthErrorCode,
	PrivateKeyJwtProvider,
	RegistrationRejectedError,
	SSEClientTransport,
	SdkHttpError,
	SseError,
	StaticPrivateKeyJwtProvider,
	StreamableHTTPClientTransport,
	UnauthorizedError,
	applyMiddlewares,
	auth,
	computeScopeUnion,
	createFetchWithInit,
	createMiddleware,
	discoverAndRequestJwtAuthGrant,
	discoverAuthorizationServerMetadata,
	discoverOAuthProtectedResourceMetadata,
	discoverOAuthServerInfo,
	fetchToken,
	isSpecType,
	isStrictScopeSuperset,
	requestJwtAuthorizationGrant,
	specTypeSchemas,
	validateClientMetadataUrl,
	withLogging,
	withOAuth,
} from "@modelcontextprotocol/client";
export type {
	AuthOptions,
	AuthProvider,
	AuthResult,
	AuthorizationServerMetadata,
	CacheEntry,
	CacheKey,
	CacheMode,
	CacheableRequestOptions,
	CallToolRequestOptions,
	CancelTaskResult,
	ClientCapabilities,
	ClientContext,
	ClientCredentialsProviderOptions,
	ClientOptions,
	CompleteRequest,
	CompleteResult,
	ConnectOptions,
	CreateTaskResult,
	CrossAppAccessContext,
	CrossAppAccessProviderOptions,
	DiscoverResult,
	FetchLike,
	GetTaskResult,
	JsonSchemaType,
	JsonSchemaValidator,
	ListChangedHandlers,
	ListChangedOptions,
	ListPromptsResult,
	ListResourceTemplatesResult,
	ListResourcesResult,
	ListTasksResult,
	ListToolsResult,
	LoggingLevel,
	LoggingOptions,
	McpSubscription,
	Middleware,
	OAuthClientInformationContext,
	OAuthClientMetadata,
	OAuthClientProvider,
	OAuthDiscoveryState,
	OAuthProtectedResourceMetadata,
	OAuthServerInfo,
	OAuthTokens,
	PriorDiscovery,
	PrivateKeyJwtProviderOptions,
	Progress,
	ProgressCallback,
	Prompt,
	ProtocolEra,
	ReconnectionScheduler,
	RequestLogger,
	RequestOptions,
	Resource,
	ResourceTemplateType,
	ResponseCacheStore,
	Root,
	SSEClientTransportOptions,
	ServerCapabilities,
	StaticPrivateKeyJwtProviderOptions,
	StoredOAuthClientInformation,
	StoredOAuthTokens,
	StreamableHTTPClientTransportOptions,
	StreamableHTTPReconnectionOptions,
	SubscriptionFilter,
	Task,
	TaskStatus,
	Tool,
	Transport,
	VersionNegotiationMode,
	VersionNegotiationOptions,
	jsonSchemaValidator,
} from "@modelcontextprotocol/client";
