export const KMCP_ERROR_CODES = Object.freeze({
	CAPABILITY_DUPLICATE: "CAPABILITY_DUPLICATE",
	CATALOG_STALE: "CATALOG_STALE",
	CATALOG_LIMIT_EXCEEDED: "CATALOG_LIMIT_EXCEEDED",
	CONNECTION_CLOSE_FAILED: "CONNECTION_CLOSE_FAILED",
	CONNECTION_CONNECT_FAILED: "CONNECTION_CONNECT_FAILED",
	CONNECTION_DUPLICATE: "CONNECTION_DUPLICATE",
	CONNECTION_GENERATION_STALE: "CONNECTION_GENERATION_STALE",
	CONNECTION_NOT_ONLINE: "CONNECTION_NOT_ONLINE",
	CONNECTION_QUARANTINED: "CONNECTION_QUARANTINED",
	CONNECTION_UNKNOWN: "CONNECTION_UNKNOWN",
	DECORATOR_METADATA_MISSING: "DECORATOR_METADATA_MISSING",
	HUB_DUPLICATE: "HUB_DUPLICATE",
	HUB_REVISION_CONFLICT: "HUB_REVISION_CONFLICT",
	HUB_ROUTE_UNKNOWN: "HUB_ROUTE_UNKNOWN",
	HUB_UNKNOWN: "HUB_UNKNOWN",
	INVALID_DEFINITION: "INVALID_DEFINITION",
	MANAGER_CLOSED: "MANAGER_CLOSED",
	OPERATION_FAILED: "OPERATION_FAILED",
} as const);

export type KmcpErrorCode = (typeof KMCP_ERROR_CODES)[keyof typeof KMCP_ERROR_CODES];

export class KmcpError extends Error {
	readonly code: KmcpErrorCode;

	constructor(code: KmcpErrorCode, message: string, options?: ErrorOptions) {
		super(message, options);
		this.name = "KmcpError";
		this.code = code;
	}
}

export function errorCode(error: unknown): KmcpErrorCode {
	return error instanceof KmcpError ? error.code : KMCP_ERROR_CODES.OPERATION_FAILED;
}
